const WARNING_AFK_DELAY_MS = 20000; // ms

export const MAXAFKTIME = 600000; // ms
export const DELAY_WARNING = MAXAFKTIME - WARNING_AFK_DELAY_MS;
export const WARNING_AFK_DELAY_S = WARNING_AFK_DELAY_MS / 1000;
