/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 metacube_card.glb -t 
*/

import * as THREE from "three";
import { useGLTF, MeshPortalMaterial } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import glbPath from "@glb/metacube_card.glb";
import model from "@glb/0.glb";
import React, { useRef, useMemo, useEffect, Suspense } from "react";
import { useFrame } from "@react-three/fiber";
type CardGLTF = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

export const MetacubeCard = React.memo(({ nftPath }: { nftPath: string }) => {
  return (
    <Wrapper>
      <Suspense fallback={null}>
        {nftPath?.length > 0 && <Model nftPath={nftPath} />}
      </Suspense>
    </Wrapper>
  );
});

const Wrapper = React.memo(({ children }: { children: React.ReactNode }) => {
  const { nodes, materials } = useGLTF(glbPath) as unknown as CardGLTF;
  return (
    <mesh
      dispose={null}
      scale={[0.2, 0.2, 0.2]}
      geometry={nodes.Plane.geometry}
      rotation={[Math.PI / 2, 0, 0]}
      material={materials["Material.001"]}
    >
      <mesh
        position={[0, 0.005, 0]} // Slightly offset to prevent z-fighting
        scale={[0.9, 0.95, 0.95]} // Slightly smaller to fit inside the card
        geometry={nodes.Plane.geometry}
      >
        <MeshPortalMaterial resolution={256} blur={0.5}>
          {children}
        </MeshPortalMaterial>
      </mesh>
    </mesh>
  );
});

useGLTF.preload(glbPath);

type NftModelGLTF = GLTF & {
  nodes: {
    Player: THREE.Mesh;
    Cube: THREE.Mesh;
    Plane: THREE.Mesh;
    Weapon: THREE.Mesh;
    Coin1: THREE.Mesh;
    Coin3: THREE.Mesh;
    Coin2: THREE.Mesh;
  };
  materials: {
    Player: THREE.MeshPhysicalMaterial;
    Cube: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["palette.001"]: THREE.MeshStandardMaterial;
    ["palette.004"]: THREE.MeshStandardMaterial;
  };
};

function Model({ nftPath }: { nftPath: string }) {
  const { nodes, materials } = useGLTF(nftPath) as unknown as NftModelGLTF;
  const colorBack = useMemo(() => {
    return materials["Material.002"]?.color ?? new THREE.Color(0x000000);
    // materials object is keyed lookup; nftPath drives re-derivation
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [materials["Material.002"], nftPath]);
  const particlesRef = useRef<THREE.Points>(null);
  const coinRef1 = useRef<THREE.Mesh>(null);
  const coinRef2 = useRef<THREE.Mesh>(null);
  const coinRef3 = useRef<THREE.Mesh>(null);

  // Create particles geometry
  const particlesGeometry = useMemo(() => {
    const geometry = new THREE.BufferGeometry();
    const count = 100;
    const positions = new Float32Array(count * 3);

    for (let i = 0; i < count * 3; i += 3) {
      positions[i] = (Math.random() - 0.5) * 4; // x-axis spread
      positions[i + 1] = Math.random() * 4; // y-axis spread
      positions[i + 2] = (Math.random() - 0.5) * 4; // z-axis spread
    }

    geometry.setAttribute("position", new THREE.BufferAttribute(positions, 3));
    return geometry;
  }, []);

  // Dispose the geometry on unmount: R3F does not auto-dispose objects passed to <primitive>
  useEffect(() => () => particlesGeometry.dispose(), [particlesGeometry]);

  // Animate particles and coins
  useFrame(({ clock }) => {
    const time = clock.getElapsedTime();

    // Animate particles
    if (particlesRef.current) {
      particlesRef.current.rotation.y = time * 0.1;
      particlesRef.current.rotation.x = Math.sin(time * 0.3) * 0.2;
    }

    // Animate coins
    if (coinRef1.current) {
      coinRef1.current.rotation.y += 0.02;
      coinRef1.current.position.y = 1.247 + Math.sin(time * 2) * 0.1;
    }

    if (coinRef2.current) {
      coinRef2.current.rotation.y += 0.03;
      coinRef2.current.position.y = 2.017 + Math.sin(time * 1.5) * 0.15;
    }

    if (coinRef3.current) {
      coinRef3.current.rotation.y += 0.025;
      coinRef3.current.position.y = 0.614 + Math.sin(time * 2.5) * 0.08;
    }
  });

  return (
    <group
      scale={[0.575, 0.575, 0.575]}
      position={[0, 0, 0.825]}
      rotation={[-Math.PI / 2, -Math.PI, 0]}
    >
      {/* Background plane with material color */}
      <mesh>
        <boxGeometry args={[50, 50, 50]} />
        <meshPhysicalMaterial color={colorBack} side={THREE.BackSide} />
      </mesh>

      {/* Particles */}
      <points ref={particlesRef}>
        <primitive object={particlesGeometry} />
        <pointsMaterial
          size={0.001}
          color={colorBack}
          transparent
          opacity={0.6}
          sizeAttenuation
        />
      </points>

      <ambientLight intensity={1} />

      <spotLight
        position={[0, 4, 0]}
        angle={0.3}
        penumbra={0.8}
        intensity={0.2}
        color="#ffffff"
        castShadow
        target-position={[0, 1.97, 0]}
      />

      <mesh
        geometry={nodes.Player.geometry}
        material={materials.Player}
        position={[0, 1.97, 0]}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Cube}
        position={[-0.001, 0.505, 0.003]}
        scale={0.5}
        castShadow
        receiveShadow
      />
      <mesh
        geometry={nodes.Weapon.geometry}
        material={nodes.Weapon.material}
        position={nodes.Weapon.position}
        quaternion={nodes.Weapon.quaternion}
        scale={nodes.Weapon.scale}
        receiveShadow
      />
      <mesh
        ref={coinRef1}
        geometry={nodes.Coin1.geometry}
        material={materials["palette.004"]}
        position={[0.565, 1.247, 0.737]}
        rotation={[0.715, 0.536, -2.014]}
        scale={0.234}
      />
      <mesh
        ref={coinRef3}
        geometry={nodes.Coin3.geometry}
        material={materials["palette.004"]}
        position={[-0.944, 0.614, 1]}
        rotation={[0.96, -0.624, -1.083]}
        scale={0.15}
        receiveShadow
      ></mesh>
      <mesh
        ref={coinRef2}
        geometry={nodes.Coin2.geometry}
        material={materials["palette.004"]}
        position={[-0.734, 2.017, -0.409]}
        rotation={[0.468, -0.784, -1.532]}
        scale={0.293}
        receiveShadow
      ></mesh>
    </group>
  );
}

useGLTF.preload(model);
