/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 airport.glb --transform --types 
Files: airport.glb [175.83KB] > airport-transformed.glb [59.7KB] (66%)
*/

import type * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import glbPath from "../../../../assets/glb/scenes/airport.glb";
import { StaticGlbComponent } from "./StaticGlbComponent";

type GLTFResult = GLTF & {
  nodes: {
    Cube001: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshStandardMaterial;
  };
};

export function AirportModel() {
  const { nodes } = useGLTF(glbPath, true, true) as unknown as GLTFResult;
  nodes.Cube001.position.set(-300, 0, 0);
  return <StaticGlbComponent nodes={nodes} generateCollision={false} />;
}

useGLTF.preload(glbPath, true, true);
