/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -t spacecraft.glb 
*/

import type * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import glbPath from "@glb/scenes/spacecraft.glb";
import { StaticGlbComponent } from "./StaticGlbComponent";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["Material.003"]: THREE.MeshStandardMaterial;
  };
};

export function Spacecraft() {
  const { nodes } = useGLTF(glbPath, true, true) as unknown as GLTFResult;
  // nodes.Plane.position.set(0, 300, 6);
  nodes.Plane.position.set(0, 300, -80);

  return <StaticGlbComponent nodes={nodes} generateCollision={false} />;
}

useGLTF.preload(glbPath, true, true);
