/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 terrainV4.glb -t -i --format png 
Files: terrainV4.glb [304.79KB] > terrainV4-transformed.glb [99.92KB] (67%)
*/

import type * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { StaticGlbComponent } from "./StaticGlbComponent";
import glbPath from "../../../../assets/glb/scenes/terrainV4-transformed.glb";
import { useEffect } from "react";
import { layerToColor } from "../../../../helpers/layerToColor";
import { useCurrentLayer } from "../../../../hooks/useCurrentLayer";
type GLTFResult = GLTF & {
  nodes: {
    Ground: THREE.Mesh;
    Ground_1: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
    Material: THREE.MeshStandardMaterial;
  };
};

export function TerrainV4() {
  const { nodes } = useGLTF(glbPath, true, true) as unknown as GLTFResult;

  const layer = useCurrentLayer();

  useEffect(() => {
    const mat = nodes.Ground_1.material as THREE.MeshStandardMaterial;
    mat.color = layerToColor(layer);
    // nodes is loaded once via useGLTF, color mutation tied to layer only
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layer]);

  return <StaticGlbComponent nodes={nodes} generateCollision={true} />;
}

useGLTF.preload(glbPath, true, true);
