/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 towers.glb -t -i --format png 
Files: towers.glb [372.32KB] > towers-transformed.glb [145.74KB] (61%)
*/

import type * as THREE from "three";
import { useGLTF } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import { StaticGlbComponent } from "./StaticGlbComponent";
import glbPath from "../../../../assets/glb/scenes/towers-transformed.glb";
import { useEffect } from "react";
import { layerToColor } from "../../../../helpers/layerToColor";
import { useCurrentLayer } from "../../../../hooks/useCurrentLayer";
type GLTFResult = GLTF & {
  nodes: {
    Cube006: THREE.Mesh;
    Cube007: THREE.Mesh;
  };
  materials: {
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Material.006"]: THREE.MeshStandardMaterial;
  };
};

export function Towers() {
  const { nodes } = useGLTF(glbPath, true, true) as unknown as GLTFResult;
  const layer = useCurrentLayer();

  useEffect(() => {
    const mat = nodes.Cube006.material as THREE.MeshStandardMaterial;
    mat.color = layerToColor(layer);
    // nodes is loaded once via useGLTF, color mutation tied to layer only
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [layer]);

  return <StaticGlbComponent nodes={nodes} generateCollision={true} />;
}

useGLTF.preload(glbPath, true, true);
