/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -t ISS_animated_texture.glb 
*/

import * as THREE from "three";
import { useEffect, useRef } from "react";
import { type ThreeElements } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { type GLTF } from "three-stdlib";
import glbPath from "../../../assets/glb/scenes/ISS_animated_texture.glb";

type GLTFResult = GLTF & {
  nodes: {
    Plane: THREE.Mesh;
  };
  materials: {
    ["Material.001"]: THREE.MeshStandardMaterial;
  };
};

type ActionName = "PlaneAction";
type GLTFActions = Record<ActionName, THREE.AnimationAction>;

export function OrbitSpaceStation(props: ThreeElements["group"]) {
  const group = useRef<THREE.Group>(null!);
  const { nodes, materials, animations } = useGLTF(
    glbPath,
    true,
    true,
  ) as unknown as GLTFResult;
  materials["Material.001"].side = THREE.FrontSide;
  // @ts-expect-error
  const { actions } = useAnimations<GLTFActions>(animations, group);
  useEffect(() => {
    // loop through all  the animations and set them to play
    Object.values(actions).forEach((action) => {
      // @ts-expect-error animation play signature is mismatched but works
      if (action) action.play();
    });
  }, [actions]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials["Material.001"]}
          rotation={[0, 0, -Math.PI]}
        />
      </group>
    </group>
  );
}

useGLTF.preload(glbPath, true, true);
